---
deployment:
  tasks:
    - export DEPLOYPATH=/home/indrxkhf/ai-seo-platform
    - rm -rf $DEPLOYPATH/.next $DEPLOYPATH/tsconfig.tsbuildinfo
    - npm ci --production=false --prefix $DEPLOYPATH
    - npm run build --prefix $DEPLOYPATH
