---
deployment:
  tasks:
    - export DEPLOYPATH=/home/indrxkhf/aisle
    - export NPM=/opt/alt/alt-nodejs24/root/usr/lib/node_modules/npm/bin/npm
    - source /home/indrxkhf/nodevenv/aisle/24/bin/activate
    - rm -rf $DEPLOYPATH/.next $DEPLOYPATH/tsconfig.tsbuildinfo
    - $NPM ci --production=false --prefix $DEPLOYPATH
    - $NPM run build --prefix $DEPLOYPATH
