---
deployment:
  tasks:
    - export DEPLOYPATH=/home/indrxkhf/aisle
    - source /home/indrxkhf/nodevenv/aisle/24/bin/activate
    - rm -rf $DEPLOYPATH/.next $DEPLOYPATH/tsconfig.tsbuildinfo
    - npm install --prefix $DEPLOYPATH
    - npm run build --prefix $DEPLOYPATH
